= Social Network Graph Example with Neo4j


// setup


[source,cypher]
----
CREATE (rachel:User {name: "Rachel Green"})
CREATE (monica:User {name: "Monica Geller"})
CREATE (phoebe:User {name: "Phoebe Buffay"})
CREATE (joey:User {name: "Joey Tribbiani"})
CREATE (chandler:User {name: "Chandler Bing"})
CREATE (ross:User {name: "Ross Geller"})

CREATE (rachel)-[:FRIEND]->(monica)
CREATE (rachel)-[:FRIEND]->(phoebe)
CREATE (rachel)-[:FRIEND]->(joey)
CREATE (rachel)-[:FRIEND]->(chandler)
CREATE (rachel)-[:FRIEND]->(ross)

CREATE (monica)-[:FRIEND]->(phoebe)
CREATE (monica)-[:FRIEND]->(joey)
CREATE (monica)-[:FRIEND]->(chandler)
CREATE (monica)-[:FRIEND]->(ross)

CREATE (phoebe)-[:FRIEND]->(joey)
CREATE (phoebe)-[:FRIEND]->(chandler)
CREATE (phoebe)-[:FRIEND]->(ross)

CREATE (joey)-[:FRIEND]->(chandler)
CREATE (joey)-[:FRIEND]->(ross)

CREATE (chandler)-[:FRIEND]->(ross)

CREATE (monica)-[:POSTED]->(post0:Post { id: "0", text: "You don't like the game, because you suck at it." })
CREATE (phoebe)-[:POSTED]->(post1:Post { id: "1", text: "Chandler still thinks I'm pregnant and he hasn't asked me how I'm feeling or offered to carry my bags. I feel bad for the woman who ends up with him." })
CREATE (joey)-[:POSTED]->(post2:Post { id: "2", text: "Just because she went to Yale drama, she thinks she's like the greatest actress since, since, sliced bread!" })
CREATE (chandler)-[:POSTED]->(post3:Post { id: "3", text: " In my defense, it was dark and he was a very pretty guy." })
CREATE (rachel)-[:POSTED]->(post4:Post { id: "4", text: "I don't want my baby's first words to be 'How You Doing'" })
CREATE (ross)-[:POSTED]->(post5:Post { id: "5", text: "Chandler entered a Vanilla Ice look-alike contest and *won*!" })

// Comments
CREATE (post0)<-[:COMMENTED{ id: "6", text: "lol" }]-(ross)
CREATE (post1)<-[:COMMENTED{ id: "7", text: "lol" }]-(rachel)
CREATE (post2)<-[:COMMENTED{ id: "8", text: "lol" }]-(chandler)
CREATE (post3)<-[:COMMENTED{ id: "9", text: "lol" }]-(joey)
CREATE (post4)<-[:COMMENTED{ id: "10", text: "lol" }]-(phoebe)
CREATE (post5)<-[:COMMENTED{ id: "11", text: "lol" }]-(monica)


// Likes
CREATE (post0)<-[:LIKED{ id: "12", text: "Ross likes this." }]-(ross)
CREATE (post1)<-[:LIKED{ id: "13", text: "Rachel likes this." }]-(rachel)
CREATE (post2)<-[:LIKED{ id: "14", text: "Chandler likes this." }]-(chandler)
CREATE (post3)<-[:LIKED{ id: "15", text: "Joey likes this." }]-(joey)
CREATE (post4)<-[:LIKED{ id: "16", text: "Phoebe likes this." }]-(phoebe)
CREATE (post5)<-[:LIKED{ id: "17", text: "Monica likes this." }]-(monica)
----

We'll start with one to find the posts made by Rachel's friends:
[source,cypher]
----
MATCH (u:User)-[:FRIEND]-(f)-[:POSTED]->(post)
WHERE u.name = "Rachel Green"
RETURN f.name AS friend, post.text as content
----

// table

Our next query might be a slight variation on this to collect the people who have liked a post:

[source,cypher]
----
MATCH (u:User)-[:FRIEND]-(f)-[:POSTED]->(post)<-[like:LIKED]-(liker)
WHERE u.name = "Rachel Green"
RETURN f.name AS friend, post.text as content, COLLECT(liker.name) as liked_by
----

// table
 
Query could collect all actions on a post, be they likes or comments:

[source,cypher]
----
MATCH (u:User)-[:FRIEND]-(f)-[:POSTED]->(post)<-[a:LIKED|:COMMENTED]->(person) 
WHERE u.name = "Rachel Green" 
RETURN f.name AS friend, post.text AS content, 
       COLLECT({ text: a.text, person: person.name, action: TYPE(a)}) AS actions
----

// table

List All Friends of a User:

[source,cypher]
----
MATCH (rachel:User {name: "Rachel Green"})-[:FRIEND]->(friend)
RETURN friend.name AS Friend
----

// table

Users Who Commented on a Specific Post:

[source,cypher]
----
MATCH (user:User)-[:COMMENTED]->(post:Post {id: "0"})
RETURN user.name AS User, post.text AS Post
----

// table

Users Who Like the Same Posts:

[source,cypher]
----
MATCH (u1:User)-[:LIKED]->(post:Post)<-[:LIKED]-(u2:User)
WHERE u1 <> u2
RETURN u1.name AS User1, u2.name AS User2, post.id, post.text
----

// table

User Activity - Posts, Comments, and Likes:

[source,cypher]
----
MATCH (user:User)
OPTIONAL MATCH (user)-[:POSTED]->(post:Post)
OPTIONAL MATCH (user)-[:COMMENTED]->(comment:Post)
OPTIONAL MATCH (user)-[:LIKED]->(like:Post)
RETURN user.name AS User, 
       count(DISTINCT post) AS Posts, 
       count(DISTINCT comment) AS Comments, 
       count(DISTINCT like) AS Likes
ORDER BY Posts DESC, Comments DESC, Likes DESC
----

// table

To visualize the friendship relationships among all users:

[source,cypher]
----
MATCH (u1:User)-[:FRIEND]->(u2:User)
RETURN u1, u2
----

//Graph

To visualize mutual friendships:

[source,cypher]
----
MATCH (u1:User)-[:FRIEND]->(u2:User), (u2)-[:FRIEND]->(u1)
RETURN u1, u2
----

//Graph

To see friendships along with interactions like posting, commenting, and liking:

[source,cypher]
----
MATCH (user:User)-[:FRIEND]->(friend:User)
OPTIONAL MATCH (user)-[:POSTED]->(post:Post)
OPTIONAL MATCH (user)-[:COMMENTED]->(post)
OPTIONAL MATCH (user)-[:LIKED]->(post)
RETURN user, friend, post
----

//Graph

To visualize which users are central based on their interactions:

[source,cypher]
----
MATCH (user:User)
OPTIONAL MATCH (user)-[:POSTED|COMMENTED|LIKED]->(post:Post)
RETURN user, count(post) AS InteractionCount
ORDER BY InteractionCount DESC
----

//Graph

Finding friends-of-friends (Recommendation Engine):
[source,cypher]
----
MATCH (user:User {name: "Joey Tribbiani"})-[:FRIEND]->(friend)-[:FRIEND]->(fof)
WHERE NOT (user)-[:FRIEND]->(fof) AND user <> fof
RETURN fof.name AS SuggestedFriend
----

//table

















